apiVersion: v1
kind: Pod
metadata:
  name: inference
  labels:
    app: inference
spec:
  containers:
    - image: alexeyshevchuk/online_inference:v2
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5
      resources:
        requests:
          memory: "950Mi"
          cpu: "500m"
        limits:
          memory: "5Gi"
          cpu: "1000m"
      name: inference
      ports:
        - containerPort: 8000